{{- if .Values.env.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-secret
type: Opaque
stringData:
    {{- range $key, $val := .Values.env.secrets}}
    {{ $key }}: {{ $val | quote}}
    {{- end }}
{{- end }}