apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
spec:
  type: {{.Values.serviceType}}
  selector:
    app: {{.Values.name}}
  ports:
  {{- range $key, $val := .Values.ports}}
  - name: {{ $.Values.name}}-port-{{ $key }}
    port: {{ .servicePort }}
    targetPort: {{ .containerPort }}
  {{- end }}
